version: '2'

services:
  reservation-service:
    image: 'reservation-service:latest'
    build:
      context: .
    container_name: reservation-service
    ports:
      - "7072:7072"
    depends_on:
      - postgres
    environment:
      - DB_URL=jdbc:postgresql://postgres-reservation:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=12345
      - DB_PLATFORM=org.hibernate.dialect.PostgreSQLDialect

  postgres:
    image: 'postgres:14.3-alpine'
    container_name: postgres-reservation
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345