version: '2'

services:
  guest-service:
    image: 'guest-service:latest'
    build:
      context: .
    container_name: guest-service
    ports:
      - "7070:7070"
    depends_on:
      - postgres
    environment:
      - DB_URL=jdbc:postgresql://localhost:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=12345
      - DB_PLATFORM=org.hibernate.dialect.PostgreSQLDialect

  postgres:
    image: 'postgres:14.3-alpine'
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345