server:
  port: 7070

spring:
  application:
    name: inn-service
  jpa:
    hibernate:
      ddl-auto: none
      dialect: "org.hibernate.dialect.PostgreSQLDialect"
      show_sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "12345"
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:changelog/db-changelog.yml
