server:
  port: 7070

spring:
  application:
    name: inn-service
  jpa:
    hibernate:
      ddl-auto: none
      dialect: "org.hibernate.dialect.PostgreSQLDialect"
      show_sql: true
  datasource:
    url: ${DB_URL:jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:sa}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:changelog/db-changelog.yml
