server:
  port: 7072

spring:
  application:
    name: reservation-service
  jpa:
    hibernate:
      ddl-auto: none
      dialect: "org.hibernate.dialect.PostgreSQLDialect"
      show_sql: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:changelog/db-changelog.yml
